import { useState } from "react";
import { isFuture, isPast, isToday } from "date-fns";
import supabase from "../services/supabase";
import Button from "../ui/Button";
import { subtractDates } from "../utils/helpers";
import toast from "react-hot-toast";

import { bookings } from "./data-bookings";
import { cabins } from "./data-cabins";
import { guests } from "./data-guests";
import { styled } from "styled-components";

// const originalSettings = {
//   minBookingLength: 3,
//   maxBookingLength: 30,
//   maxGuestsPerBooking: 10,
//   breakfastPrice: 15,
// };

async function deleteGuests() {
  const { error } = await supabase.from("guests").delete().gt("id", 0);
  if (error) {
    console.error("Error deleting guests:", error);
    toast.error(`Error deleting guests: ${error.message}`);
    throw error;
  }
}

async function deleteCabins() {
  const { error } = await supabase.from("cabins").delete().gt("id", 0);
  if (error) {
    console.error("Error deleting cabins:", error);
    toast.error(`Error deleting cabins: ${error.message}`);
    throw error;
  }
}

async function deleteBookings() {
  const { error } = await supabase.from("bookings").delete().gt("id", 0);
  if (error) {
    console.error("Error deleting bookings:", error);
    toast.error(`Error deleting bookings: ${error.message}`);
    throw error;
  }
}

async function createGuests() {
  // Remove id and created_at as they are auto-generated by the database
  const guestsToInsert = guests.map(({ id, created_at, ...guest }) => guest);
  const { error } = await supabase.from("guests").insert(guestsToInsert);
  if (error) {
    console.error("Error creating guests:", error);
    toast.error(`Error creating guests: ${error.message}`);
    throw error;
  }
}

async function createCabins() {
  // Remove id as it is auto-generated by the database
  const cabinsToInsert = cabins.map(({ id, ...cabin }) => cabin);
  const { error } = await supabase.from("cabins").insert(cabinsToInsert);
  if (error) {
    console.error("Error creating cabins:", error);
    toast.error(`Error creating cabins: ${error.message}`);
    throw error;
  }
}

async function createBookings() {
  // Bookings need a guestId and a cabinId. We can't tell Supabase IDs for each object, it will calculate them on its own. So it might be different for different people, especially after multiple uploads. Therefore, we need to first get all guestIds and cabinIds, and then replace the original IDs in the booking data with the actual ones from the DB
  const { data: guestsIds } = await supabase
    .from("guests")
    .select("id")
    .order("id");
  const allGuestIds = guestsIds.map((guest) => guest.id);
  const { data: cabinsIds } = await supabase
    .from("cabins")
    .select("id")
    .order("id");
  const allCabinIds = cabinsIds.map((cabin) => cabin.id);

  const finalBookings = bookings.map((booking) => {
    // Find the cabin by its index (cabinId 1 = index 0, etc.)
    const cabin = cabins[booking.cabinId - 1];
    
    // Find the guest index in the original guests array
    const guestIndex = guests.findIndex(g => g.id === booking.guestId);
    
    const numNights = subtractDates(booking.endDate, booking.startDate);
    const cabinPrice = numNights * (cabin.regularprice - cabin.discount);
    const extrasPrice = booking.hasBreakfast
      ? numNights * 15 * booking.numGuests
      : 0; // hardcoded breakfast price
    const totalPrice = cabinPrice + extrasPrice;

    let status;
    if (
      isPast(new Date(booking.endDate)) &&
      !isToday(new Date(booking.endDate))
    )
      status = "checked-out";
    if (
      isFuture(new Date(booking.startDate)) ||
      isToday(new Date(booking.startDate))
    )
      status = "unconfirmed";
    if (
      (isFuture(new Date(booking.endDate)) ||
        isToday(new Date(booking.endDate))) &&
      isPast(new Date(booking.startDate)) &&
      !isToday(new Date(booking.startDate))
    )
      status = "checked-in";

    return {
      created_at: booking.created_at,
      startdate: booking.startDate,
      enddate: booking.endDate,
      numnights: numNights,
      numguests: booking.numGuests,
      cabinprice: cabinPrice,
      extrasprice: extrasPrice,
      totalprice: totalPrice,
      guestid: allGuestIds[guestIndex],
      cabinid: allCabinIds[booking.cabinId - 1],
      hasbreakfast: booking.hasBreakfast,
      ispaid: booking.isPaid,
      observations: booking.observations,
      status,
    };
  });

  console.log(finalBookings);

  const { error } = await supabase.from("bookings").insert(finalBookings);
  if (error) {
    console.error("Error creating bookings:", error);
    toast.error(`Error creating bookings: ${error.message}`);
    throw error;
  }
}

function Uploader() {
  const [isLoading, setIsLoading] = useState(false);

  async function uploadAll() {
    setIsLoading(true);
    try {
      // Bookings need to be deleted FIRST
      toast.loading("Deleting old data...");
      await deleteBookings();
      await deleteGuests();
      await deleteCabins();

      toast.loading("Creating guests...");
      await createGuests();
      
      toast.loading("Creating cabins...");
      await createCabins();
      
      toast.loading("Creating bookings...");
      await createBookings();

      toast.success("✅ All sample data uploaded successfully!");
    } catch (error) {
      console.error("Upload failed:", error);
      toast.error(`Upload failed: ${error.message}`);
    } finally {
      setIsLoading(false);
    }
  }

  async function uploadBookings() {
    setIsLoading(true);
    try {
      toast.loading("Deleting old bookings...");
      await deleteBookings();
      
      toast.loading("Creating new bookings...");
      await createBookings();
      
      toast.success("✅ Bookings uploaded successfully!");
    } catch (error) {
      console.error("Upload failed:", error);
      toast.error(`Upload failed: ${error.message}`);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <StyledUploader>
      <h3>SAMPLE DATA</h3>

      <Button onClick={uploadAll} disabled={isLoading}>
        Upload ALL
      </Button>

      <Button onClick={uploadBookings} disabled={isLoading}>
        Upload bookings ONLY
      </Button>
    </StyledUploader>
  );
}

export default Uploader;

const StyledUploader = styled.div`
  margin-top: auto;
  background-color: var(--color-silver-100);
  padding: 8px;
  border-radius: 5px;
  text-align: center;
  display: flex;
  flex-direction: column;
  gap: 8px;
`;
